# Generated by Django 6.0.2 on 2026-02-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('browser', models.CharField(blank=True, default='', max_length=50)),
                ('browser_version', models.CharField(blank=True, default='', max_length=20)),
                ('os', models.CharField(blank=True, default='', max_length=50)),
                ('os_version', models.CharField(blank=True, default='', max_length=20)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('referrer', models.URLField(blank=True, default='', max_length=2048)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortenedurl')),
            ],
            options={
                'verbose_name': 'Click Event',
                'verbose_name_plural': 'Click Events',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['shortened_url', 'clicked_at'], name='analytics_c_shorten_40de7a_idx'), models.Index(fields=['country'], name='analytics_c_country_68430a_idx')],
            },
        ),
    ]
