# Generated by Django 6.0.2 on 2026-02-07 15:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(db_index=True, max_length=2048)),
                ('short_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_custom_code', models.BooleanField(default=False, help_text='Whether the short code was chosen by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date. Null means never expires.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Denormalized click counter for fast reads.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortened_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'is_active'], name='shortener_s_created_90cebe_idx'), models.Index(fields=['short_code', 'is_active'], name='shortener_s_short_c_327481_idx')],
            },
        ),
    ]
